# Generated by Django 4.0.3 on 2022-09-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibManagSysApp', '0002_rename_name_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_retal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
